// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// bcdC
Rcpp::List bcdC(SEXP Br, SEXP Omegar, SEXP BInitr, SEXP OmegaInitr, SEXP Yr, int maxIter, int sigConv, double maxKap, double tol, double omegaInitScale);
RcppExport SEXP BCD_bcdC(SEXP BrSEXP, SEXP OmegarSEXP, SEXP BInitrSEXP, SEXP OmegaInitrSEXP, SEXP YrSEXP, SEXP maxIterSEXP, SEXP sigConvSEXP, SEXP maxKapSEXP, SEXP tolSEXP, SEXP omegaInitScaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type Br(BrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Omegar(OmegarSEXP);
    Rcpp::traits::input_parameter< SEXP >::type BInitr(BInitrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type OmegaInitr(OmegaInitrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Yr(YrSEXP);
    Rcpp::traits::input_parameter< int >::type maxIter(maxIterSEXP);
    Rcpp::traits::input_parameter< int >::type sigConv(sigConvSEXP);
    Rcpp::traits::input_parameter< double >::type maxKap(maxKapSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type omegaInitScale(omegaInitScaleSEXP);
    __result = Rcpp::wrap(bcdC(Br, Omegar, BInitr, OmegaInitr, Yr, maxIter, sigConv, maxKap, tol, omegaInitScale));
    return __result;
END_RCPP
}
