# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bcdC <- function(Br, Omegar, BInitr, OmegaInitr, Yr, maxIter, sigConv, maxKap, tol, omegaInitScale) {
    .Call('BCD_bcdC', PACKAGE = 'BCD', Br, Omegar, BInitr, OmegaInitr, Yr, maxIter, sigConv, maxKap, tol, omegaInitScale)
}

sem_el_fit_obj <- function(b_weights_r, y_r, b_r, moment_2_restrictions_r, moment_3_restrictions_r, moment_4_restrictions_r, tol, max_iter, meanEst) {
    .Call('BCD_sem_el_fit_obj', PACKAGE = 'BCD', b_weights_r, y_r, b_r, moment_2_restrictions_r, moment_3_restrictions_r, moment_4_restrictions_r, tol, max_iter, meanEst)
}

sem_el_fit_weights <- function(b_weights_r, y_r, b_r, moment_2_restrictions_r, moment_3_restrictions_r, moment_4_restrictions_r, tol, max_iter, meanEst) {
    .Call('BCD_sem_el_fit_weights', PACKAGE = 'BCD', b_weights_r, y_r, b_r, moment_2_restrictions_r, moment_3_restrictions_r, moment_4_restrictions_r, tol, max_iter, meanEst)
}

sem_el_naive_fit_obj <- function(weights_r, y_r, omega_r, b_r, dual_r, tol, max_iter, meanEst) {
    .Call('BCD_sem_el_naive_fit_obj', PACKAGE = 'BCD', weights_r, y_r, omega_r, b_r, dual_r, tol, max_iter, meanEst)
}

sem_el_naive_fit_weights <- function(weights_r, y_r, omega_r, b_r, dual_r, tol, max_iter, meanEst) {
    .Call('BCD_sem_el_naive_fit_weights', PACKAGE = 'BCD', weights_r, y_r, omega_r, b_r, dual_r, tol, max_iter, meanEst)
}

sem_el_fit_obj_one_fixed <- function(b_weights_r, y_r, b_r, moment_2_restrictions_r, moment_3_restrictions_r, tol, max_iter, meanEst, b_fixed, row_ind, col_ind) {
    .Call('BCD_sem_el_fit_obj_one_fixed', PACKAGE = 'BCD', b_weights_r, y_r, b_r, moment_2_restrictions_r, moment_3_restrictions_r, tol, max_iter, meanEst, b_fixed, row_ind, col_ind)
}

sem_el_euclid_fit_obj <- function(b_weights_r, y_r, b_r, moment_2_restrictions_r, moment_3_restrictions_r, moment_4_restrictions_r, meanEst) {
    .Call('BCD_sem_el_euclid_fit_obj', PACKAGE = 'BCD', b_weights_r, y_r, b_r, moment_2_restrictions_r, moment_3_restrictions_r, moment_4_restrictions_r, meanEst)
}

sem_el_euclid_fit_weights <- function(b_weights_r, y_r, b_r, moment_2_restrictions_r, moment_3_restrictions_r, moment_4_restrictions_r, meanEst) {
    .Call('BCD_sem_el_euclid_fit_weights', PACKAGE = 'BCD', b_weights_r, y_r, b_r, moment_2_restrictions_r, moment_3_restrictions_r, moment_4_restrictions_r, meanEst)
}

sem_el_fit_obj_l1 <- function(b_weights_r, y_r, b_r, moment_2_restrictions_r, moment_3_restrictions_r, moment_4_restrictions_r, tol, max_iter, meanEst, penalty) {
    .Call('BCD_sem_el_fit_obj_l1', PACKAGE = 'BCD', b_weights_r, y_r, b_r, moment_2_restrictions_r, moment_3_restrictions_r, moment_4_restrictions_r, tol, max_iter, meanEst, penalty)
}

